version: 2
registries:
  npm-registry-npm-shopify-io-node:
    type: npm-registry
    url: https://npm.shopify.io/node
    token: ${{secrets.NPM_REGISTRY_NPM_SHOPIFY_IO_NODE_TOKEN}}
updates:
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 100
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"
