projects:
  default:
    schema: 'node_modules/@shopify/hydrogen/storefront.schema.json'
    documents:
      - '!*.d.ts'
      - '*.{ts,tsx,js,jsx}'
      - 'app/**/*.{ts,tsx,js,jsx}'
  customer-account:
    schema: 'node_modules/@shopify/hydrogen/customer-account.schema.json'
    documents:
      - '!*.d.ts'
      - '*.{ts,tsx,js,jsx}'
      - 'app/**/*.{ts,tsx,js,jsx}'
    extensions:
      languageService:
        gqlTagOptions:
          annotationSuffix: customer
