name: Add issues/PRs to project boards

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  oxygen-board:
    name: add-to-oxygen-board
    runs-on: shopify-ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/Shopify/projects/4534
          github-token: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
