name: Weekly ship Version Packages
on:
  schedule:
    - cron: '0 9 * * 2' # Run the workflow every Tuesday at 9am UTC
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  version_packages:
    runs-on: shopify-ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get PR number
        id: get-pr
        run: |
          PR_NUMBER=$(curl --request GET \
            --url 'https://api.github.com/repos/${{ github.repository }}/pulls' \
            --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'Accept: application/vnd.github.v3+json' | jq '.[] | select(.user.login=="shopify-github-actions-access[bot]" and .title=="Version Packages") | .number' | head -1)
          if [ -z "$PR_NUMBER" ]; then
            echo "Couldn't get Version Packages PR number" && exit 0
          fi
          echo "number=$PR_NUMBER" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        if: steps.get-pr.outputs.number != ''
        run: npm ci
        working-directory: ./.github/actions/add-comment-to-pr-number

      - name: Add shipit comment
        if: steps.get-pr.outputs.number != ''
        uses: ./.github/actions/add-comment-to-pr-number
        with:
          github-token: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
          pr-number: ${{ steps.get-pr.outputs.number }}
          comment: '/shipit'
