name: Dependabot Auto-Merge
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  approve-dependabot-pr:
    runs-on: shopify-ubuntu-latest
    if: ${{ github.triggering_actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          skip-verification: true
      - name: Auto-merge Dependabot PRs
        uses: Shopify/github-actions/dependabot-auto-merge-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          metadata: ${{ toJSON(steps.metadata.outputs) }}
