name: 'Mark or close stale issues and PRs'
on:
  schedule:
    - cron: '30 14 * * 1-5' # dependabot runs at 10am ET; run this 30 mins later to get 1 day staleness

jobs:
  stale:
    runs-on: shopify-ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          days-before-stale: 90
          days-before-close: -1
          days-before-pr-close: 100
          exempt-issue-labels: gsd,epic
          exempt-pr-labels: dependencies
          remove-stale-when-updated: true
          repo-token: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
  stale-dependabot:
    runs-on: shopify-ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          only-pr-labels: 'dependencies'
          stale-pr-label: 'atc'
          days-before-pr-stale: 1
          days-before-pr-close: -1
          remove-stale-when-updated: false
          repo-token: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
